export default {
    "page_title" : "ورود",
    "email" : "ایمیل",    
    "password" : "کلمه عبور",
    "forgot_password" : "بازیابی حساب کاربری",  
    "login" : "ورود",
    "validation_email_required" : "لطفا ایمیل را وارد نمایید.",
    "validation_email_email" : "ایمیل باید معتبر باشد.",
    "validation_password_required" : "لطفا کلمه عبور را وارد نمایید.",
    "login_failed" : "ایمیل یا کلمه عبور صحیح نمی باشد.",
    "login_account_disabled" : "حساب کاربری شما غیرفعال می باشد.",
    "login_account_blocked" : "حساب کاربری شما مسدود می باشد.",
    "no_access" : "برای دسترسی به پنل مدیریت باید ابتدا وارد شوید.",
    "login_success_logout" : "شما با موفقیت خارج شدید.",
    "profile" : "ویرایش پروفایل",
    "profile_save" : "ذخیره",
    "profile_back" : "بازگشت",
    "profile_first_name" : "نام",
    "profile_last_name" : "نام خانوادگی",
    "profile_email" : "ایمیل",
    "profile_pass1" : "کلمه عبور جاری",
    "profile_pass2" : "کلمه عبور جدید",
    "profile_pass3" : "تکرار کلمه عبور جدید",
    "profile_avatar" : "تصویر",
};